apiVersion: v1
kind: ConfigMap
metadata:
  name: doctron
  namespace: default
data:
  doctron-config.yaml: |+
    doctron:
      maxConvertWorker: 50
      env: dev
      retry: true
      maxConvertQueue: 60
      convertTimeout: 10
      uploader: alioss
      domain: 0.0.0.0:8080
      TLSCertFile: certfile
      TLSKeyFile: keyfile
      user:
        - username: doctron
          password: lampnick
        - username: nick2
          password: lampnick2
    oss:
      endpoint:
      accessKeyId:
      accessKeySecret:
      bucketName:
      privateServerDomain:

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: doctron-deploy
  name: doctron-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      name: doctron-deploy
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: doctron-deploy
    spec:
      containers:
      - name: doctron-service
        image: lampnick/doctron
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 2048m
            memory: 4Gi
          requests:
            cpu: 800m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /doctron.yaml
            name: doctron
            subPath: doctron-config.yaml
      restartPolicy: Always
      volumes:
      - name: doctron
        configMap:
          name: doctron
          defaultMode: 0777
          items:
            - key: doctron-config.yaml
              path: doctron-config.yaml
