version: "2.1"
services:
  myimdb_mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=32505856 --net_read_timeout=700 --default-storage-engine=MyIsam
    container_name: MOVIELIB_Mysql
    restart: always
    ports:
    - ${MYSQL_MYIMDB_PORT}:${MYSQL_MYIMDB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_MYIMDB_PASS}
      MYSQL_TCP_PORT: ${MYSQL_MYIMDB_PORT}
    volumes:
    - ${MYSQL_MYIMDB_DB_LOCATION}:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "$MYSQL_MYIMDB_HOST", "-P$MYSQL_MYIMDB_PORT"]
      timeout: 20s
      retries: 50

  imdb_update_service:
    network_mode: host
    container_name: MOVIELIB_imdb
    build:
      context: ./
      dockerfile: Dockerfile_MOVIELIB_imdb
    env_file:
      - .env
    restart: on-failure
    depends_on:
      myimdb_mysql:
        condition: service_healthy

  omdb_update_service:
    container_name: MOVIELIB_omdb
    network_mode: host
    build:
      context: ./
      dockerfile: Dockerfile_MOVIELIB_omdb
    env_file:
      - .env
    restart: on-failure
    depends_on:
      myimdb_mysql:
        condition: service_healthy

  tmdb_update_service:
    container_name: MOVIELIB_tmdb
    network_mode: host
    build:
      context: ./
      dockerfile: Dockerfile_MOVIELIB_tmdb
    env_file:
      - .env
    restart: on-failure
    depends_on:
      myimdb_mysql:
        condition: service_healthy
