version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - ${PLEX_FILES_LOCATION}:/config
      - ${PLEX_TV_LIBRARY_FOLDER}:/tv
      - ${PLEX_MOVIES_LIBRARY_FOLDER}:/movies
    restart: unless-stopped

  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=${TRANSMISSION_USER} #optional
      - PASS=${TRANSMISSION_PASS} #optional
    volumes:
      - ${TRANSMISSION_FILES_LOCATION}:/config
      - ${TRANSMISSION_FILES_LOCATION}/downloads:/downloads
      - ${TRANSMISSION_FILES_LOCATION}/watch:/watch
      - ${PLEX_TV_LIBRARY_FOLDER}:/tv
      - ${PLEX_MOVIES_LIBRARY_FOLDER}:/movies
      - /mnt/Media/books/downloads:/books
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
# TODO add volume here for mysql persistance
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    network_mode: host
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_TCP_PORT: 5433
    volumes:
    - ${MYSQL_DB_LOCATION}:/var/lib/mysql

  imdb_update_service:
    build:
      context: ./
      dockerfile: Dockerfile_imdb_db_update_service
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - mysql

  omdb_update_service:
    build:
      context: ./
      dockerfile: Dockerfile_omdb_db_update_service
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - mysql

  tmdb_update_service:
    build:
      context: ./
      dockerfile: Dockerfile_tmdb_db_update_service
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - mysql

  imdb_sync_service:
    build:
      context: ./
      dockerfile: Dockerfile_MyImdb_sync_service
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - mysql

  filelist_service:
    build:
      context: ./
      dockerfile: Dockerfile_filelist_service
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - mysql
      - torrent_service

  torrent_service:
    build:
      context: ./
      dockerfile: Dockerfile_torrent_service
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - mysql
      - transmission

  telegram_service:
    build:
      context: ./
      dockerfile: Dockerfile_telegram_service
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - mysql
      - transmission
